version: "3.9"
services:
  nginx-react:
    container_name: nginx-react
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
    - 80:80
    environment:
      NODE_ENV: production
  test:
    container_name: test
    build:
      context: "."
      dockerfile: "Dockerfile_local"
    ports:
    - 80:80
    environment:
      NODE_ENV: development